travel-reservation/travel-reservation-war/src/java/com/flights/jsf/FlightsManagedBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.flights.jsf;

import com.airport.entity.Airport;
import com.flights.entity.Flight;
import com.airport.sessionbean.AirportFacade;
import com.flights.sessionbean.FlightFacade;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.ejb.EJB;

/**
 *
 * @author Rustam Drake
 */
@Named(value = "flightsManagedBean")
@SessionScoped
public class FlightsManagedBean implements Serializable {

    /**
     * Creates a new instance of FlightsManagedBean
     */
    public FlightsManagedBean() {
    }

    @EJB
    FlightFacade flightFacade;
    @EJB
    AirportFacade airportFacade;

    private String airportName;
    private String to;
    private String from;
    private String toAirportName;
    private String fromAirportName;
    private String iata;
    private int flightNo;
    private Date flightDate;
    private Date flightTime;
    private int business;
    private int economy;

    public List<Airport> getAllAirports() {
        return airportFacade.findAll();
    }

    /**
     * @return message for the selected airports
     */
    public String getMessageFromAirportsSelection() {
        if ("".equals(from) || from == null || "".equals(to) || to == null) {
            return "";
        } else if (from.equals(to)) {
            return "YOU CAN'T SELECT THE SAME AIRPORT";
        } else {
            return "Flights from " + airportFacade.airportNameFromIATA(from)
                    + " to " + airportFacade.airportNameFromIATA(to) + ":";
        }
    }

    /**
     *
     * @return a String of all flight numbers flying from 'from' airport to 'to'
     * airport
     */
    public String getFlightNoFromToFlightsAsString() {
        String temp = "";
        temp = flightFacade.fromToFlights(from, to).stream().map((f)
                -> f.getFlightNumber() + ", ").reduce(temp, String::concat);
        if ("".equals(temp)) {
            return "";
        } else {
            return temp;
        }
    }

    /**
     *
     * @return
     */
    public List<Flight> getFromToFlights() {
        if (flightFacade.fromToFlights(from, to) == null) {
            return null;
        } else {
            return flightFacade.fromToFlights(from, to);
        }
    }

    /**
     * called when a flight has been selected from the table in the booking home
     *
     * @param flight
     * @return sends you to the booking page
     */
    public String goToBookingPage(Flight flight) {
        this.flightNo = flight.getFlightNumber();
        this.flightDate = flight.getFlight_Date();
        this.flightTime = flight.getFlight_Time();
        this.from = flight.getFrom_Airport();
        this.to = flight.getTo_Airport();
        this.toAirportName = airportFacade.airportNameFromIATA(to);
        this.fromAirportName = airportFacade.airportNameFromIATA(from);
        getNumberOfSeatsAvailable(flightNo);
        return "booking_page";
    }
    /**
     * get the number of seats available for the given flight number
     * @param flightNo 
     */
    private void getNumberOfSeatsAvailable(int flightNo){
        this.business = flightFacade.getInfoForFlightNo(flightNo).getBusiness();
        this.economy = flightFacade.getInfoForFlightNo(flightNo).getEconomy();
    }
    //getters & setters bellow
    public String getTo() {
        return to;
    }

    public void setTo(String to) {
        this.to = to;
    }

    public String getFrom() {
        return from;
    }

    public void setFrom(String from) {
        this.from = from;
    }

    public String getAirportName() {
        return airportName;
    }

    public void setAirportName(String airportName) {
        this.airportName = airportName;
    }

    public String getIata() {
        return iata;
    }

    public void setIata(String iata) {
        this.iata = iata;
    }

    public int getFlightNo() {
        return flightNo;
    }

    public void setFlightNo(int flightNo) {
        this.flightNo = flightNo;
    }

    public Date getFlightDate() {
        return flightDate;
    }

    public void setFlightDate(Date flightDate) {
        this.flightDate = flightDate;
    }

    public Date getFlightTime() {
        return flightTime;
    }

    public void setFlightTime(Date flightTime) {
        this.flightTime = flightTime;
    }

    public String getToAirportName() {
        return toAirportName;
    }

    public void setToAirportName(String toAirportName) {
        this.toAirportName = toAirportName;
    }

    public String getFromAirportName() {
        return fromAirportName;
    }

    public void setFromAirportName(String fromAirportName) {
        this.fromAirportName = fromAirportName;
    }

    public int getBusiness() {
        return business;
    }

    public void setBusiness(int business) {
        this.business = business;
    }

    public int getEconomy() {
        return economy;
    }

    public void setEconomy(int economy) {
        this.economy = economy;
    }

}

travel-reservation/travel-reservation-war/web/booking/booking_home.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Booking Info page</title>
    </h:head>
    <h:body>
        <div>
            <h2>Booking Info page</h2>
            <h4>Choose your From: and To: airports and the press 'GO!' and see 
                the info for those airports
            </h4>
            <f:view>
                <h:form>
                    <h:panelGrid columns="2">
                        From :
                        <h:selectOneMenu value="#{flightsManagedBean.from}" id="item1">
                            <f:selectItems value="#{flightsManagedBean.allAirports}" 
                                           var="airport1" itemValue="#{airport1.iataCode}" 
                                           itemLabel="#{airport1.airportName} - #{airport1.iataCode}" />
                        </h:selectOneMenu>
                        To :
                        <h:selectOneMenu value="#{flightsManagedBean.to}" id="item2">
                            <f:selectItems value="#{flightsManagedBean.allAirports}" 
                                           var="airport2" itemValue="#{airport2.iataCode}" 
                                           itemLabel="#{airport2.airportName} - #{airport2.iataCode}" />
                        </h:selectOneMenu>
                        Look up :
                        <h:commandButton value="Go!" >
                            <f:ajax execute="@form" event="click" render="flights_information"/>
                            <f:ajax execute="@form" event="click" render="info"/>
                        </h:commandButton>
                    </h:panelGrid>

                    <h:outputText id="flights_information" value="Message: #{flightsManagedBean.messageFromAirportsSelection}"/>

                    <!--table for resulting selection -->
                    <h:dataTable value="#{flightsManagedBean.fromToFlights}" var="item" border="1" id="info">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText  value="From"/>
                            </f:facet>
                            <h:outputText value="#{item.from_Airport}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="To"/>
                            </f:facet>
                            <h:outputText value="#{item.to_Airport}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="Departure Date"/>
                            </f:facet>
                            <h:outputText value="#{item.flight_Date}">
                                <f:convertDateTime pattern="dd/MM/yyyy" timeZone="CET"/>
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="Departure Time"/>
                            </f:facet>
                            <h:outputText value="#{item.flight_Time}">
                                <f:convertDateTime pattern="HH:mm" timeZone="CET"/>
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="Duration"/>
                            </f:facet>
                            <h:outputText value="#{item.flight_Duration}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="Flight No."/>
                            </f:facet>
                            <h:outputText value="#{item.flightNumber}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="Seats available"/>
                            </f:facet>
                            <h:outputText value="#{item.business + item.economy} "/>
                        </h:column>
                       


                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="Select One"/>
                            </f:facet>
                            <h:commandButton value="Book!" action=
                                             "#{flightsManagedBean.goToBookingPage(item)}">
                            </h:commandButton>
                        </h:column>
                    </h:dataTable>
                </h:form>


                <h:form>
                    <ui:fragment rendered="#{loginController.email!=null}">
                        <h:commandButton style="position: fixed; top: 0; right: 0; text-align: right" 
                                         value="Logout" action="#{loginController.logout()}"/>
                    </ui:fragment>
                    <ui:fragment rendered="#{loginController.email==null}">
                        <p style="position: fixed; top: 0; right: 0; text-align: right"> 
                            go back to the <h:link value="home page " outcome="/index.xhtml"/> and login
                        </p>
                    </ui:fragment>
                </h:form>

            </f:view>
            <div style="position: absolute">
                <p style="position: fixed; bottom: 0; width:100%; text-align: left">
                    <h:link value="HOME " outcome="/index.xhtml"/>
                </p>
            </div>
        </div>
    </h:body>
</html>

travel-reservation/travel-reservation-war/web/booking/booking_page.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <head>
        <title>TODO supply a title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <h:body>
        <h:form>
            <ui:fragment rendered="#{loginController.email==null}">
                Please login in order to book your flight
            </ui:fragment>
            <ui:fragment rendered="#{loginController.email!=null}">
                You wish to book the flight number #{flightsManagedBean.flightNo}<br/>
                The flight is from #{flightsManagedBean.fromAirportName} to #{flightsManagedBean.toAirportName} 
                on <h:outputText value="#{flightsManagedBean.flightDate}">
                    <f:convertDateTime pattern="dd/MM/yyyy" timeZone="CET"/>
                </h:outputText>
                at <h:outputText value="#{flightsManagedBean.flightTime}">
                    <f:convertDateTime pattern="HH:mm" timeZone="CET"/>
                </h:outputText> <br/>
                Available #{flightsManagedBean.business} business seats available <br/>
                Available #{flightsManagedBean.economy} economy seats available <br/><br/>
                Logged in details as following<br/>
                Full Name: #{account.getAccountNameFull(loginController.email)} <br/>
                Please choose the number of seats and the seat class

                <h:panelGrid columns="2">
                    Business:
                    <h:inputText size="5" value="#{reservation.businessReserved}"/>
                    Economy
                    <h:inputText size="5" value="#{reservation.economyReserved}"/>
                    <h:commandButton  value="Reserve/Pay" 
                                      action="#{reservation.reserve(flightsManagedBean.flightNo, loginController.email)}"/>
                </h:panelGrid>

            </ui:fragment>
        </h:form>



        <h:form>
            <ui:fragment rendered="#{loginController.email!=null}">
                <h:commandButton style="position: fixed; top: 0; right: 0; text-align: right" 
                                 value="Logout" action="#{loginController.logout()}"/>
            </ui:fragment>
            <ui:fragment rendered="#{loginController.email==null}">
                <h:commandButton style="position: fixed; top: 0; right: 0; text-align: right"
                                 value="Login" action="/index.xhtml"/>
            </ui:fragment>
        </h:form>
        <div style="position: absolute">
            <p style="position: fixed; bottom: 0; width:100%; text-align: left">
                <h:link value="HOME " outcome="/index.xhtml"/>
            </p>
        </div>
    </h:body>
</html>

travel-reservation/travel-reservation-war/web/booking/pay.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <head>
        <title>reserve and pay page</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <h:body>
        <h:form>
            You have reserve a flight Number #{flightsManagedBean.flightNo} with #{reservation.businessReserved} 
            business seats and #{reservation.economyReserved} economy seats  reserved<br/>

            Current Credit Card details on your profile: <br/>
            Credit Card Number: #{account.getCardNumber(loginController.email)} <br/>
            Credit Card Expiration Date: #{account.getCardExpirationDate(loginController.email)} <br/>

            <h:commandButton value="Pay"
                             action="#{reservation.pay()}"/>

        </h:form>
        <h:form>
            <ui:fragment rendered="#{loginController.email!=null}">
                <h:commandButton style="position: fixed; top: 0; right: 0; text-align: right" 
                                 value="Logout" action="#{loginController.logout()}"/>
            </ui:fragment>
            <ui:fragment rendered="#{loginController.email==null}">
                <h:commandButton style="position: fixed; top: 0; right: 0; text-align: right"
                                 value="Login" action="/index.xhtml"/>
            </ui:fragment>
        </h:form>
        <div style="position: absolute">
            <p style="position: fixed; bottom: 0; width:100%; text-align: left">
                <h:link value="HOME " outcome="/index.xhtml"/>
            </p>
        </div>
    </h:body>
</html>

travel-reservation/travel-reservation-war/web/booking/payment_accepted.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>payment </title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body>
        <div>payment accepted</div>
        
        
    </body>
</html>

travel-reservation/travel-reservation-war/web/booking/payment_error.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>error</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body>
        <div>payment was not complete</div>
    </body>
</html>

travel-reservation/travel-reservation-war/web/booking/too_many_seats_reserved.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>error</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body>
        <div> Can not reserve more seats than available, go back!!!</div>
    </body>
</html>